#!/usr/bin/env bash
# Status script for dwm
# colours: 01:normal 02:white 03:red 04:green 05:yellow 06:blue
# 07:cyan 08:magenta 09:grey

# Copyright (c) 2013-2017 Jason W Ryan
# The MIT License (MIT) http://opensource.org/licenses/MIT

org(){
    org="$(emacsclient -e '
    (when (bound-and-true-p org-clock-current-task)
         (concat"  " (string-trim (substring-no-properties (org-clock-get-clock-string))))))')"
    echo $org | sed 's/^nil$//g; s/["()\[]//g' | sed 's/\]/ -/g'
 }

net(){
    wifi="$(wifi)"
    vpn="$(vpn status)"
    if [[ $vpn ]]; then
        printf "%b" " $wifi"
    else
        printf "%b" " $wifi"
    fi
}
vol(){
    vol="$(pamixer --get-volume)"
    mute="$(pamixer --get-mute)"
    if $mute; then
        printf "%b" " "
    else
        printf "%b" " $vol"
    fi
}
bat(){
    onl="$(</sys/class/power_supply/ADP1/online)"
    charge="$(</sys/class/power_supply/BAT0/capacity)"
    if [[ $onl -eq 0 ]]; then
        printf "%b" " $charge%"
    else
        printf "%b" " $charge%"
    fi
}

# Pipe to status bar
xsetroot -name "$(org) $(vol) $(net) $(bat)"
