#!/bin/sh

#org(){
#    org="$(emacsclient -e '
#    (when (bound-and-true-p org-clock-current-task)
#         (concat"  " (string-trim (substring-no-properties (org-clock-get-clock-string))))))')"
#    echo $org | sed 's/^nil$//g; s/["()\[]//g' | sed 's/\]/ -/g'
# }

net(){
    wifi="$(wifi)"
    vpn="$(vpn status)"
    if [[ $vpn ]]; then
        printf "%b" " $wifi"
    else
        printf "%b" " $wifi"
    fi
}
vol(){
    vol="$(volume level)"
    mute="$(volume status)"
    if [ "$mute" = "yes" ] ; then
        printf "%b" " "
    else
        printf "%b" " $vol"
    fi
}
bat(){
    onl="$(</sys/class/power_supply/ADP1/online)"
    charge="$(</sys/class/power_supply/BAT0/capacity)"
    if [[ $onl -eq 0 ]]; then
        printf "%b" " $charge%"
    else
        printf "%b" " $charge%"
    fi
}
dte(){
   dte="$(date "+%a %l:%M %p")"
   printf "%b" "$dte"
}

# Pipe to status bar
xsetroot -name "$(net) $(bat) $(vol) $(dte)"
