#!/bin/sh

cd ~/Virtual
qemu-system-x86_64 -enable-kvm -m 2048 -nic user,model=virtio -drive file=disks/openbsd.qcow2,media=disk,if=virtio -cdrom media/install64.iso -vga virtio -net user,hostfwd=tcp::10022-:22
